server:
  port: 7002 # Indicate the default PORT where this service will be started

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:7001/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: player-service

security:
  ignored : /**